version: '2.1'
services:
  cloud-config-server:
    image: "demo/cloud-config-server"
    environment:
      EUREKA_SERVER_NAME: ${EUREKA_SERVER_NAME}
      CONFIG_SERVER_NAME: ${CONFIG_SERVER_NAME}
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cloud-config-server:8888/actuator/health"]
      interval: 5s
      retries: 20

  cloud-gateway:
    image: "demo/cloud-gateway"
    environment:
      EUREKA_SERVER_NAME: ${EUREKA_SERVER_NAME}
      CONFIG_SERVER_NAME: ${CONFIG_SERVER_NAME}
    ports:
      - "9999:9999"
    links:
      - cloud-eureka-server
      - cloud-config-server
    depends_on:
      cloud-eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cloud-gateway:9999/actuator/health"]
      interval: 5s
      retries: 20

  cloud-eureka-server:
    image: "demo/cloud-eureka-server"
    environment:
      EUREKA_SERVER_NAME: ${EUREKA_SERVER_NAME}
      CONFIG_SERVER_NAME: ${CONFIG_SERVER_NAME}
    ports:
      - "8761:8761"
    links:
      - cloud-config-server
    depends_on:
      cloud-config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cloud-eureka-server:8761/actuator/health"]
      interval: 5s
      retries: 20

  cloud-hystrix-dashboard:
    image: "demo/cloud-hystrix-dashboard"
    environment:
      EUREKA_SERVER_NAME: ${EUREKA_SERVER_NAME}
      CONFIG_SERVER_NAME: ${CONFIG_SERVER_NAME}
    ports:
      - "7979:7979"
    links:
      - cloud-eureka-server
      - cloud-config-server
    depends_on:
      cloud-eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cloud-hystrix-dashboard:7979/actuator/health"]
      interval: 5s
      retries: 20

  sales-order:
    image: "demo/sales-order"
    environment:
      EUREKA_SERVER_NAME: ${EUREKA_SERVER_NAME}
      CONFIG_SERVER_NAME: ${CONFIG_SERVER_NAME}
    ports:
      - "8080:8080"
    links:
      - cloud-eureka-server
      - cloud-config-server
    depends_on:
      cloud-eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://sales-order:8080/actuator/health"]
      interval: 5s
      retries: 20

  delivery-tracking:
    image: "demo/delivery-tracking"
    environment:
      EUREKA_SERVER_NAME: ${EUREKA_SERVER_NAME}
      CONFIG_SERVER_NAME: ${CONFIG_SERVER_NAME}
    ports:
      - "8081:8081"
    links:
      - cloud-eureka-server
      - cloud-config-server
    depends_on:
      cloud-eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://delivery-tracking:8081/actuator/health"]
      interval: 5s
      retries: 20

  mytruck-api:
    image: "demo/mytruck-api"
    environment:
      EUREKA_SERVER_NAME: ${EUREKA_SERVER_NAME}
      CONFIG_SERVER_NAME: ${CONFIG_SERVER_NAME}
    ports:
      - "8082:8082"
    links:
      - cloud-eureka-server
      - cloud-config-server
    depends_on:
      cloud-eureka-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://mytruck-api:8082/actuator/health"]
      interval: 5s
      retries: 20

