apiVersion: v1
kind: Service
metadata:
  name: cloud-config-server
  labels:
    run: cloud-config-server
spec:
  ports:
  - port: 8888
    protocol: TCP
  selector:
    run: cloud-config-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-server
spec:
  selector:
    matchLabels:
      run: cloud-config-server
  replicas: 1
  template:
    metadata:
      labels:
        run: cloud-config-server
    spec:
      containers:
      - name: cloud-config-server
        image: "${your-docker-hub-prefix}/cloud-config-server"
        ports:
        - containerPort: 8888
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8888
          initialDelaySeconds: 20
          periodSeconds: 20
        env:
        - name: EUREKA_SERVER_NAME
          value: "cloud-eureka-server"
        - name: CONFIG_SERVER_NAME
          value: "cloud-config-server"
      imagePullSecrets:
        - name: ${your-k8s-registry-key}

---

apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway
  labels:
    run: cloud-gateway
spec:
  ports:
  - port: 9999
    protocol: TCP
  selector:
    run: cloud-gateway

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-gateway
spec:
  selector:
    matchLabels:
      run: cloud-gateway
  replicas: 1
  template:
    metadata:
      labels:
        run: cloud-gateway
    spec:
      containers:
      - name: cloud-gateway
        image: "${your-docker-hub-prefix}/cloud-gateway"
        ports:
        - containerPort: 9999
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 9999
          initialDelaySeconds: 20
          periodSeconds: 20
        env:
        - name: EUREKA_SERVER_NAME
          value: "cloud-eureka-server"
        - name: CONFIG_SERVER_NAME
          value: "cloud-config-server"
      imagePullSecrets:
        - name: ${your-k8s-registry-key}

---

apiVersion: v1
kind: Service
metadata:
  name: cloud-eureka-server
  labels:
    run: cloud-eureka-server
spec:
  ports:
  - port: 8761
    protocol: TCP
  selector:
    run: cloud-eureka-server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-eureka-server
spec:
  selector:
    matchLabels:
      run: cloud-eureka-server
  replicas: 1
  template:
    metadata:
      labels:
        run: cloud-eureka-server
    spec:
      containers:
      - name: cloud-eureka-server
        image: "${your-docker-hub-prefix}/cloud-eureka-server"
        ports:
        - containerPort: 8761
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 20
          periodSeconds: 20
        env:
        - name: EUREKA_SERVER_NAME
          value: "cloud-eureka-server"
        - name: CONFIG_SERVER_NAME
          value: "cloud-config-server"
      imagePullSecrets:
        - name: ${your-k8s-registry-key}

---

apiVersion: v1
kind: Service
metadata:
  name: cloud-hystrix-dashboard
  labels:
    run: cloud-hystrix-dashboard
spec:
  ports:
  - port: 7979
    protocol: TCP
  selector:
    run: cloud-hystrix-dashboard

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-hystrix-dashboard
spec:
  selector:
    matchLabels:
      run: cloud-hystrix-dashboard
  replicas: 1
  template:
    metadata:
      labels:
        run: cloud-hystrix-dashboard
    spec:
      containers:
      - name: cloud-hystrix-dashboard
        image: "${your-docker-hub-prefix}/cloud-hystrix-dashboard"
        ports:
        - containerPort: 7979
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 7979
          initialDelaySeconds: 20
          periodSeconds: 20
        env:
        - name: EUREKA_SERVER_NAME
          value: "cloud-eureka-server"
        - name: CONFIG_SERVER_NAME
          value: "cloud-config-server"
      imagePullSecrets:
        - name: ${your-k8s-registry-key}

---

apiVersion: v1
kind: Service
metadata:
  name: sales-order
  labels:
    run: sales-order
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: sales-order

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sales-order
spec:
  selector:
    matchLabels:
      run: sales-order
  replicas: 1
  template:
    metadata:
      labels:
        run: sales-order
    spec:
      containers:
      - name: sales-order
        image: "${your-docker-hub-prefix}/sales-order"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 20
        env:
        - name: EUREKA_SERVER_NAME
          value: "cloud-eureka-server"
        - name: CONFIG_SERVER_NAME
          value: "cloud-config-server"
      imagePullSecrets:
        - name: ${your-k8s-registry-key}

---

apiVersion: v1
kind: Service
metadata:
  name: delivery-tracking
  labels:
    run: delivery-tracking
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    run: delivery-tracking

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-tracking
spec:
  selector:
    matchLabels:
      run: delivery-tracking
  replicas: 1
  template:
    metadata:
      labels:
        run: delivery-tracking
    spec:
      containers:
      - name: delivery-tracking
        image: "${your-docker-hub-prefix}/delivery-tracking"
        ports:
        - containerPort: 8081
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 20
          periodSeconds: 20
        env:
        - name: EUREKA_SERVER_NAME
          value: "cloud-eureka-server"
        - name: CONFIG_SERVER_NAME
          value: "cloud-config-server"
      imagePullSecrets:
        - name: ${your-k8s-registry-key}

---

apiVersion: v1
kind: Service
metadata:
  name: mytruck-api
  labels:
    run: mytruck-api
spec:
  ports:
  - port: 8082
    protocol: TCP
  selector:
    run: mytruck-api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytruck-api
spec:
  selector:
    matchLabels:
      run: mytruck-api
  replicas: 1
  template:
    metadata:
      labels:
        run: mytruck-api
    spec:
      containers:
      - name: mytruck-api
        image: "${your-docker-hub-prefix}/mytruck-api"
        ports:
        - containerPort: 8082
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8082
          initialDelaySeconds: 20
          periodSeconds: 20
        env:
        - name: EUREKA_SERVER_NAME
          value: "cloud-eureka-server"
        - name: CONFIG_SERVER_NAME
          value: "cloud-config-server"
      imagePullSecrets:
        - name: ${your-k8s-registry-key}

---

